### ISSUE TITLE
what is the format of "llava_val_coco_fmt.json"

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#16]
In file vigc/tasks/caption_train_eval.py [https://github.com/opendatalab/VIGC/blob/main/vigc/tasks/caption_train_eval.py#L14](url) , there is "ANN_FILE = "/mnt/petrelfs/hanxiao/working/llava_process/llava_val_coco_fmt.json"
what is the format about it?

**Comment by shipengai** [comment]
when I change ANN_FILE to llava_val.json that is downloaded by [https://drive.google.com/drive/folders/1yFTZlMR1KoFrPiVBYNncVsw5zOEKbj0s](url)
```
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    main()
  File "train.py", line 100, in main
    runner.train()
  File "/workdir/vigc/runners/runner_base.py", line 377, in train
    val_log = self.eval_epoch(
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workdir/vigc/runners/runner_base.py", line 466, in eval_epoch
    return self.task.after_evaluation(
  File "/workdir/vigc/tasks/caption_train_eval.py", line 128, in after_evaluation
    metrics = self._report_metrics(
  File "/workdir/vigc/common/dist_utils.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/workdir/vigc/tasks/caption_train_eval.py", line 143, in _report_metrics
    eval_ret = cocoeval.compute_metrics(cocoeval.results)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/mmpretrain/evaluation/metrics/caption.py", line 90, in compute_metrics
    coco_val = coco_caption_eval(eval_result_file, self.ann_file)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/mmpretrain/evaluation/metrics/caption.py", line 120, in coco_caption_eval
    coco = COCO(ann_file)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/pycocotools/coco.py", line 83, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
AssertionError: annotation file format <class 'list'> not supported
```

**Comment by wufan-tb** [comment]
it's a coco format llava data, we extracted it from llava150k as an eval set, you can make up with following format:

```
{"annotations": [
    {"question_id": xxx, "image": "xxx", "question": "xxx?", "answer": ["xxx"]},
    ..., 
]
}
```

considering your bug report, perhaps you can try to wrap the list in llava_val.json to a dict, with a key named "annotations".

**Comment by shipengai** [comment]
@wufan-tb Can you share this file？
```
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    main()
  File "train.py", line 100, in main
    runner.train()
  File "/workdir/vigc/runners/runner_base.py", line 377, in train
    val_log = self.eval_epoch(
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workdir/vigc/runners/runner_base.py", line 466, in eval_epoch
    return self.task.after_evaluation(
  File "/workdir/vigc/tasks/caption_train_eval.py", line 130, in after_evaluation
    metrics = self._report_metrics(
  File "/workdir/vigc/common/dist_utils.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/workdir/vigc/tasks/caption_train_eval.py", line 145, in _report_metrics
    eval_ret = cocoeval.compute_metrics(cocoeval.results)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/mmpretrain/evaluation/metrics/caption.py", line 90, in compute_metrics
    coco_val = coco_caption_eval(eval_result_file, self.ann_file)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/mmpretrain/evaluation/metrics/caption.py", line 121, in coco_caption_eval
    coco_result = coco.loadRes(results_file)
  File "/workdir/conda_envs/vigc/lib/python3.8/site-packages/pycocotools/coco.py", line 314, in loadRes
    res.dataset['images'] = [img for img in self.dataset['images']]
KeyError: 'images'
```

**Comment by wufan-tb** [comment]
sure, I uploaded this file to google drive, you can download from here: https://drive.google.com/file/d/1efNW7_I4uOh-KBfbPLDQe83SphrSm35T/view?usp=sharing
